# -*- coding: utf-8 -*-
"""Untitled10.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17YXVk7uUbcpJPpm7_wVHxtL6aJAxZRR5
"""

def calcular_promedio(lista_numeros):
    """
    Calcula el promedio de una lista de números.

    Parámetros: lista_numeros (list): Lista de valores numéricos.

    Retorna: float: Promedio de los números de la lista.
    """

    if len(lista_numeros) == 0:
        return 0
    return sum(lista_numeros) / len(lista_numeros)

numeros = [10, 8, 9, 7, 6]
promedio = calcular_promedio(numeros)

print("El promedio es:", promedio)